---
- name: Install latest version of "zabbix-agent"
  apt:
    name: "{{ zabbix_agent_package }}"
    state: latest
  when: ansible_pkg_mgr == "apt"
  become: true
  become_user: root
  register: install_zabbix_agent
  async: 3600
  poll: 3
  tags:
    - install
    - zabbix-agent

- import_tasks: zabbix-config.yml
